### ISSUE TITLE
Cross references to Trixi.jl

### ISSUE THREAD

**Issue by patrickersing** [trixi-framework/TrixiShallowWater.jl#32]
As mentioned in the comment below, we might need to fix the cross references to Trixi.jl:
```suggestion
- [`AnalysisCallback`](@ref) analyzes this variable.
+ [`AnalysisCallback`](https://trixi-framework.github.io/Trixi.jl/stable/reference-trixi/#Trixi.AnalysisCallback)
analyzes this variable.
```
I do not think that we can cross reference via `@ref` because this function info is in the Trixi docs. Thus, I think we need a direct link, or am I wrong @sloede ?

_Originally posted by @andrewwinters5000 in https://github.com/trixi-framework/TrixiShallowWater.jl/pull/30#discussion_r1539112292_

**Comment by sloede** [comment]
This might be the solution (note: I have never used it myself, just saw it on the Julia Slack `#appreciation` channel):
https://github.com/JuliaDocs/DocumenterInterLinks.jl

**Comment by patrickersing** [comment]
Thanks for the suggestion! I like the solution with `DocumenterInterLinks.jl`. It was easy to setup and is very convenient to create the external references.

**Comment by patrickersing** [comment]
It is very nice that with the introduction of `DocumenterInterLinks.jl`, we now get error messages and the documentation test fails if a reference could not be resolved (see https://github.com/trixi-framework/TrixiShallowWater.jl/actions/runs/8645007736/job/23701318957?pr=40#step:7:94).
